# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set environment varibles
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set work directory
WORKDIR /usr/src/app

# Install any needed packages specified directly
RUN pip install --no-cache-dir {{ requirements | join(" ") }}

RUN pip install uvicorn starlette

# Copy the current directory contents into the container at /usr/src/app
COPY . .

# Run the application
CMD ["uvicorn", "{{ app_module }}", "--host", "0.0.0.0", "--port", "8090"]
